# Generated by Django 3.2.10 on 2021-12-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_visitors_leaving_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='checked_out',
        ),
    ]
