# Generated by Django 3.2.10 on 2021-12-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_visitors_checked_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='leaving_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
